# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true

reviews:
  profile: "assertive"
  high_level_summary: true
  collapse_walkthrough: false
  review_status: false

  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
    base_branches:
      - dev
      - alpha
